# Define the name of the Python interpreter
PYTHON = python

# Define the name of the Python scripts
SCRAPER = scrape_data.py
UPLOAD = upload_aws.py

# Define targets to run the Python scripts
scrape:
	$(PYTHON) $(SCRAPER)

upload:
	$(PYTHON) $(UPLOAD)